apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
patches:
- path: agic-watch-all-namespaces.yaml
  target:
    kind: ConfigMap
    name: ingress-appgw-cm
    namespace: kube-system
    labelSelector: "app: ingress-appgw"