apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: yelb
  namespace: yelb
  annotations:
    kubernetes.io/ingress.class: azure/application-gateway
  labels:
    app: yelb
spec:
  rules:
    - http:
        paths:
          - path: /*
            pathType: Prefix
            backend:
              service: 
                name: yelb-ui
                port: 
                  number: 80