apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: yelb-admins
  namespace: yelb
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: admin
subjects:
- apiGroup: rbac.authorization.k8s.io
  kind: Group
  name: '23e31ded-a0b2-408b-ad2d-cc1ed3c70cf7'
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: guestbook-admins
  namespace: guestbook
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: admin
subjects:
- apiGroup: rbac.authorization.k8s.io
  kind: Group
  name: '23e31ded-a0b2-408b-ad2d-cc1ed3c70cf7'